@startuml
left to right direction
actor Пользователь
actor Директор
actor РуководительОтдела
actor РуководительПодотдела
actor Сотрудник

rectangle "Система управления событиями и встречами" {
  Пользователь -- (Регистрация)
  Пользователь -- (Вход в систему)
  Пользователь -- (Просмотр и редактирование профиля)
  Пользователь -- (Выбор режима работы)
  Пользователь -- (Просмотр уведомлений)
  Пользователь -- (Отправка/получение личных встреч)
  Пользователь -- (Создание шаблонов личных встреч)
  Пользователь -- (Управление расписанием доступности)
  Пользователь -- (Просмотр событий и встреч)
  Пользователь -- (Добавление заметок к встрече)

  Директор -- (Создание компании)
  Директор -- (Рассмотрение заявок на вступление)
  Директор -- (Создание/редактирование/удаление отделов)
  Директор -- (Назначение руководителей отделов)
  Директор -- (Создание/удаление подотделов)
  Директор -- (Назначение руководителей подотделов)
  Директор -- (Добавление/удаление сотрудников)
  Директор -- (Назначение/отзыв ролей)
  Директор -- (Создание событий и встреч)
  Директор -- (Просмотр всех сотрудников компании)

  РуководительОтдела -- (Создание/редактирование/удаление подотделов)
  РуководительОтдела -- (Назначение руководителей подотделов)
  РуководительОтдела -- (Добавление/удаление сотрудников в отдел/подотдел)
  РуководительОтдела -- (Создание событий и встреч)

  РуководительПодотдела -- (Добавление/удаление сотрудников в подотдел)
  РуководительПодотдела -- (Создание событий и встреч)

  Сотрудник -- (Просмотр своих событий и встреч)
  Сотрудник -- (Участие в событиях и встречах)
}

@enduml
